@startuml
class Editeur {
    - texte : String
    - pressePapier : PressePapier
    - selection : Selection

    + selectText() : String
    + removeText() : void
    + ReplaceText(text:String) : void
    + addText(text:String) : void
    + copier() : void
    + couper() : void
    + coller() : void
}

class PressePapier{
    - content : String
    + copier() : void
    + coller() : void
}

class Selection {
    - start : int
    - end : int
    + update() : void
}

Interface Command {
    + execute() : void
}

class Couper {
    - buffer : String
    + execute() : void
}

class Copier {
    - buffer : String
    + execute() : void
}

class Coller {
    - buffer : String
    + execute() : void
}

class SelectionCommand {
    - buffer : String
    + execute() : void
}

class Invoker {
    - command : Command
    + executeCommand(Command cmd) : void
}



' Relations

Editeur <-- Command
Command <|.. Copier
Command <|.. Couper
Command <|.. Coller
Command <|.. SelectionCommand

Editeur <-- PressePapier : "1..1"
Editeur <-- Selection : "1..1"
Invoker --> Command : "1..*"


@enduml
