@startuml
actor Utilisateur
participant InterfaceGraphique
participant Editeur
participant Historique
participant Memento
participant PressePapier
participant Selection

Utilisateur -> InterfaceGraphique : collerAction()
InterfaceGraphique -> Editeur : sauvegarderEtat()
Editeur -> Historique : ajouterCommande(new Coller(), creerMemento())
Editeur -> Memento : creerMemento()
Memento -> Editeur : retourne texte, start, end

Editeur -> PressePapier : get()
PressePapier --> Editeur : retourne texteDuPressePapier

Editeur -> Selection : getStart()
Editeur -> Selection : getEnd()
Editeur -> Editeur : coller texteDuPressePapier

Editeur -> Historique : ajouterCommande(Command : Coller, Memento)
@enduml
