@startuml
left to right direction
skinparam packageStyle rectangle

:Client: as client


    
rectangle "Editeur de texte"{

client ---> (Ecrire texte)

client ---> (Coller)

client ---> (Selectionner texte)
(Selectionner texte) .> (Copier) : include
(Selectionner texte) .> (Couper) : include
(Selectionner texte) ..> (Remplacer) : include

}


@enduml
